server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true

spring:
  application:
    name: data-service